name: "Sign"

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sign:
    runs-on: ubuntu-24.04
    env:
      TERM: xterm
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Import GPG key
        run: |
          gpg_tmp="$(mktemp).gpg"
          echo "${{ secrets.GPG_SIGNING_KEY }}" > "${gpg_tmp}"
          gpg --import "${gpg_tmp}"
          rm -f "${gpg_tmp}"
          unset gpg_tmp
      - name: Publish
        run: |
          set -e
            git config --global user.email "jeaye@jank-lang.org"
            git config --global user.name "Jeaye Wilkerson"
            git config --global commit.gpgsign true

            git fetch
            git checkout gh-pages
            git merge main --allow-unrelated-histories
            ./bin/update
            ./bin/sign
            git commit --allow-empty -am "[automated] Publish latest release"
            git push origin gh-pages
          set +e
